"""Apply corrections and open the fix PR (Phases.md Phase 4.1).

All GitHub/git access goes through the injected GitHubBackend protocol so the
pipeline stays testable offline (Rules.md §5, §7).
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Protocol

from dochealer.config import FIX_BRANCH_PREFIX, FIX_LABEL, Settings
from dochealer.models import Correction, LinkGraph

log = logging.getLogger(__name__)


class GitHubBackend(Protocol):
    """Side-effect surface; FakeGitHub in tests, PyGithub+git in production."""

    def create_fix_branch(self, branch: str) -> None: ...
    def commit_files(self, branch: str, files: dict[str, str], message: str) -> None: ...
    def open_pr(self, branch: str, title: str, body: str, label: str) -> str:
        """Returns the new PR's URL."""
        ...
    def upsert_comment(self, pr_number: int, marker: str, body: str) -> None: ...


def apply_corrections_to_files(
    corrections: list[Correction], graph: LinkGraph, repo_root: Path
) -> dict[str, str]:
    """Splice corrected sections into their doc files; returns path -> new content.

    Sections are replaced bottom-up per file so earlier line numbers stay valid.
    """
    by_file: dict[str, list[Correction]] = {}
    for correction in corrections:
        section = graph.section_by_id(correction.section_id)
        if section is None:
            log.warning("[report] unknown section %s; skipping", correction.section_id)
            continue
        by_file.setdefault(section.path, []).append(correction)

    out: dict[str, str] = {}
    for path, items in by_file.items():
        text = (repo_root / path).read_text(encoding="utf-8")
        lines = text.splitlines()
        sections = [(graph.section_by_id(c.section_id), c) for c in items]
        for section, correction in sorted(sections, key=lambda t: -t[0].lineno):
            new_lines = correction.new_content.splitlines()
            # preserve the blank-line gap before the next section: LLMs often trim it
            old_lines = lines[section.lineno - 1 : section.end_lineno]
            while old_lines and not old_lines[-1].strip():
                if new_lines and not new_lines[-1].strip():
                    break
                new_lines.append("")
                old_lines.pop()
            lines[section.lineno - 1 : section.end_lineno] = new_lines
        out[path] = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    return out


def fix_pr_body(corrections: list[Correction], graph: LinkGraph, source_pr: int) -> str:
    """Per Design.md §5: one block per fix, reason quoted, review checklist."""
    blocks = [f"## 🩹 Doc fixes for #{source_pr}\n"]
    for correction in corrections:
        section = graph.section_by_id(correction.section_id)
        title = section.title if section else correction.section_id
        path = section.path if section else "?"
        blocks.append(
            f"`{path}` › **{title}**\n> {correction.summary}\n\n"
            f"_Generated by dochealer · validated · confidence {correction.confidence:.2f}_\n"
        )
    blocks.append(
        "Review checklist: [ ] accurate  [ ] style preserved  [ ] nothing over-deleted"
    )
    return "\n".join(blocks)


def create_fix_pr(
    corrections: list[Correction],
    graph: LinkGraph,
    settings: Settings,
    backend: GitHubBackend,
) -> str:
    """Create branch + commit + PR for the auto-fixes; returns PR URL."""
    branch = f"{FIX_BRANCH_PREFIX}{settings.pr_number}"
    files = apply_corrections_to_files(corrections, graph, settings.repo_root)
    if not files:
        return ""
    backend.create_fix_branch(branch)
    backend.commit_files(
        branch, files,
        f"docs: fix {len(corrections)} stale section(s) for #{settings.pr_number}",
    )
    url = backend.open_pr(
        branch,
        f"docs: fixes for #{settings.pr_number}",
        fix_pr_body(corrections, graph, settings.pr_number),
        FIX_LABEL,
    )
    log.info("[report] opened fix PR %s (%d files)", url, len(files))
    return url
